import Text "mo:base/Text";
import Array "mo:base/Array";

persistent actor {
    // This is the function your React App will call
    // It takes the image bytes ([Nat8]) and returns the generated React/Tailwind code (Text)
    public func process_doodle(image_data : [Nat8]) : async Text {
        
        // 1. In a full implementation, this is where you make an 
        // HTTP outcall to OpenAI/Anthropic Vision API.
        
        // 2. For now, let's return a "Success" message to test the connection
        // once you're ready, we can add the actual AI API call logic here.
        
        let mockResponse = "/* Generated by Duiodle AI */ \n <div className='p-8 bg-slate-900 text-white'>Your Sketch is now Code!</div>";
        
        return mockResponse;
    };

    // Keeping your info function but updated for Duiodle
    public query func getInfo() : async { appName : Text; tagline : Text } {
        {
            appName = "Duiodle";
            tagline = "Transforming doodles into interfaces.";
        };
    };
};